const mongoose = require('mongoose');

const Schema = mongoose.Schema;
const ObjectId = Schema.ObjectId;

const PlanetSchema = new Schema({
  kepid: String,
  kepoi_name: String,
  kepler_name: String,
  koi_disposition: String,
  koi_pdisposition: String,
  koi_score: String,
  koi_fpflag_nt: String,
  koi_fpflag_ss: String,
  koi_fpflag_co: String,
  koi_fpflag_ec: String,
  koi_period: String,
  koi_period_err1: String,
  koi_period_err2: String,
  koi_time0bk: String,
  koi_time0bk_err1: String,
  koi_time0bk_err2: String,
  koi_impact: String,
  koi_impact_err1: String,
  koi_impact_err2: String,
  koi_duration: String,
  koi_duration_err1: String,
  koi_duration_err2: String,
  koi_depth: String,
  koi_depth_err1: String,
  koi_depth_err2: String,
  koi_prad: String,
  koi_prad_err1: String,
  koi_prad_err2: String,
  koi_teq: String,
  koi_teq_err1: String,
  koi_teq_err2: String,
  koi_insol: String,
  koi_insol_err1: String,
  koi_insol_err2: String,
  koi_model_snr: String,
  koi_tce_plnt_num: String,
  koi_tce_delivname: String,
  koi_steff: String,
  koi_steff_err1: String,
  koi_steff_err2: String,
  koi_slogg: String,
  koi_slogg_err1: String,
  koi_slogg_err2: String,
  koi_srad: String,
  koi_srad_err1: String,
  koi_srad_err2: String,
  ra: String,
  dec: String,
  koi_kepmag: String,
});
const Planet = mongoose.model('Planet', PlanetSchema);
module.exports = Planet;